export enum MESSAGE_ALIAS {
    DELETE_TABLE = "DELETE_TABLE",
    DUPLICATE_RECORD = "DUPLICATE_RECORD",
    DUPLICATE_TABLE = "DUPLICATE_TABLE",
    EDIT_RECORD = "EDIT_RECORD",
    EDIT_TABLE_NAME = "EDIT_TABLE_NAME",
    INSERT_RECORD = "INSERT_RECORD",
    DELETE_RECORD = "DELETE_RECORD",
    GET_PRIMARY_KEYS = "GET_PRIMARY_KEYS",
    GET_TABLES = "GET_TABLES",
    GET_TABLE = "GET_TABLE"
}
